// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AsebaNativeFunctionParameter extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static AsebaNativeFunctionParameter getRootAsAsebaNativeFunctionParameter(ByteBuffer _bb) { return getRootAsAsebaNativeFunctionParameter(_bb, new AsebaNativeFunctionParameter()); }
  public static AsebaNativeFunctionParameter getRootAsAsebaNativeFunctionParameter(ByteBuffer _bb, AsebaNativeFunctionParameter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AsebaNativeFunctionParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long size() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createAsebaNativeFunctionParameter(FlatBufferBuilder builder,
      int nameOffset,
      long size) {
    builder.startTable(2);
    AsebaNativeFunctionParameter.addSize(builder, size);
    AsebaNativeFunctionParameter.addName(builder, nameOffset);
    return AsebaNativeFunctionParameter.endAsebaNativeFunctionParameter(builder);
  }

  public static void startAsebaNativeFunctionParameter(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addSize(FlatBufferBuilder builder, long size) { builder.addInt(1, (int) size, (int) 0L); }
  public static int endAsebaNativeFunctionParameter(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AsebaNativeFunctionParameter get(int j) { return get(new AsebaNativeFunctionParameter(), j); }
    public AsebaNativeFunctionParameter get(AsebaNativeFunctionParameter obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

