// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Breakpoint extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Breakpoint getRootAsBreakpoint(ByteBuffer _bb) { return getRootAsBreakpoint(_bb, new Breakpoint()); }
  public static Breakpoint getRootAsBreakpoint(ByteBuffer _bb, Breakpoint obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Breakpoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long line() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createBreakpoint(FlatBufferBuilder builder,
      long line) {
    builder.startTable(1);
    Breakpoint.addLine(builder, line);
    return Breakpoint.endBreakpoint(builder);
  }

  public static void startBreakpoint(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addLine(FlatBufferBuilder builder, long line) { builder.addInt(0, (int) line, (int) 0L); }
  public static int endBreakpoint(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Breakpoint get(int j) { return get(new Breakpoint(), j); }
    public Breakpoint get(Breakpoint obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

