// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CompilationResultSuccess extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static CompilationResultSuccess getRootAsCompilationResultSuccess(ByteBuffer _bb) { return getRootAsCompilationResultSuccess(_bb, new CompilationResultSuccess()); }
  public static CompilationResultSuccess getRootAsCompilationResultSuccess(ByteBuffer _bb, CompilationResultSuccess obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CompilationResultSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long bytecodeSize() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long totalBytecodeSize() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long variablesSize() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long totalVariablesSize() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createCompilationResultSuccess(FlatBufferBuilder builder,
      long requestId,
      long bytecodeSize,
      long totalBytecodeSize,
      long variablesSize,
      long totalVariablesSize) {
    builder.startTable(5);
    CompilationResultSuccess.addTotalVariablesSize(builder, totalVariablesSize);
    CompilationResultSuccess.addVariablesSize(builder, variablesSize);
    CompilationResultSuccess.addTotalBytecodeSize(builder, totalBytecodeSize);
    CompilationResultSuccess.addBytecodeSize(builder, bytecodeSize);
    CompilationResultSuccess.addRequestId(builder, requestId);
    return CompilationResultSuccess.endCompilationResultSuccess(builder);
  }

  public static void startCompilationResultSuccess(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addBytecodeSize(FlatBufferBuilder builder, long bytecodeSize) { builder.addInt(1, (int) bytecodeSize, (int) 0L); }
  public static void addTotalBytecodeSize(FlatBufferBuilder builder, long totalBytecodeSize) { builder.addInt(2, (int) totalBytecodeSize, (int) 0L); }
  public static void addVariablesSize(FlatBufferBuilder builder, long variablesSize) { builder.addInt(3, (int) variablesSize, (int) 0L); }
  public static void addTotalVariablesSize(FlatBufferBuilder builder, long totalVariablesSize) { builder.addInt(4, (int) totalVariablesSize, (int) 0L); }
  public static int endCompilationResultSuccess(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CompilationResultSuccess get(int j) { return get(new CompilationResultSuccess(), j); }
    public CompilationResultSuccess get(CompilationResultSuccess obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

