// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class CompilationOptions {
  private CompilationOptions() { }
  public static final long NoOption = 1;
  public static final long LoadOnTarget = 2;
  public static final long FetchBytecode = 4;
}

