// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CompileAndLoadCodeOnVM extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static CompileAndLoadCodeOnVM getRootAsCompileAndLoadCodeOnVM(ByteBuffer _bb) { return getRootAsCompileAndLoadCodeOnVM(_bb, new CompileAndLoadCodeOnVM()); }
  public static CompileAndLoadCodeOnVM getRootAsCompileAndLoadCodeOnVM(ByteBuffer _bb, CompileAndLoadCodeOnVM obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CompileAndLoadCodeOnVM __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public mobsya.fb.NodeId nodeId() { return nodeId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeId(mobsya.fb.NodeId obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int language() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 1; }
  public String program() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer programAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer programInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long options() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createCompileAndLoadCodeOnVM(FlatBufferBuilder builder,
      long requestId,
      int nodeIdOffset,
      int language,
      int programOffset,
      long options) {
    builder.startTable(5);
    CompileAndLoadCodeOnVM.addOptions(builder, options);
    CompileAndLoadCodeOnVM.addProgram(builder, programOffset);
    CompileAndLoadCodeOnVM.addLanguage(builder, language);
    CompileAndLoadCodeOnVM.addNodeId(builder, nodeIdOffset);
    CompileAndLoadCodeOnVM.addRequestId(builder, requestId);
    return CompileAndLoadCodeOnVM.endCompileAndLoadCodeOnVM(builder);
  }

  public static void startCompileAndLoadCodeOnVM(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNodeId(FlatBufferBuilder builder, int nodeIdOffset) { builder.addOffset(1, nodeIdOffset, 0); }
  public static void addLanguage(FlatBufferBuilder builder, int language) { builder.addInt(2, language, 1); }
  public static void addProgram(FlatBufferBuilder builder, int programOffset) { builder.addOffset(3, programOffset, 0); }
  public static void addOptions(FlatBufferBuilder builder, long options) { builder.addInt(4, (int) options, (int) 0L); }
  public static int endCompileAndLoadCodeOnVM(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 10);  // program
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CompileAndLoadCodeOnVM get(int j) { return get(new CompileAndLoadCodeOnVM(), j); }
    public CompileAndLoadCodeOnVM get(CompileAndLoadCodeOnVM obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

