// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EnableThymio2PairingMode extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static EnableThymio2PairingMode getRootAsEnableThymio2PairingMode(ByteBuffer _bb) { return getRootAsEnableThymio2PairingMode(_bb, new EnableThymio2PairingMode()); }
  public static EnableThymio2PairingMode getRootAsEnableThymio2PairingMode(ByteBuffer _bb, EnableThymio2PairingMode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EnableThymio2PairingMode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enable() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }

  public static int createEnableThymio2PairingMode(FlatBufferBuilder builder,
      boolean enable) {
    builder.startTable(1);
    EnableThymio2PairingMode.addEnable(builder, enable);
    return EnableThymio2PairingMode.endEnableThymio2PairingMode(builder);
  }

  public static void startEnableThymio2PairingMode(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addEnable(FlatBufferBuilder builder, boolean enable) { builder.addBoolean(0, enable, true); }
  public static int endEnableThymio2PairingMode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EnableThymio2PairingMode get(int j) { return get(new EnableThymio2PairingMode(), j); }
    public EnableThymio2PairingMode get(EnableThymio2PairingMode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

