// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class ErrorType {
  private ErrorType() { }
  public static final int no_error = 0;
  /**
   * Genric error
   */
  public static final int unknown_error = 1;
  /**
   * The node ddoes not exist or was disconnected
   */
  public static final int unknown_node = 2;
  /**
   * The node is busy (locked by another client)
   */
  public static final int node_busy = 3;
  /**
   *Unsuported variable type - For SetVariables and Events
   */
  public static final int unsupported_variable_type = 4;
  public static final int thymio2_pairing_write_dongle_failed = 5;
  public static final int thymio2_pairing_write_robot_failed = 6;

  public static final String[] names = { "no_error", "unknown_error", "unknown_node", "node_busy", "unsupported_variable_type", "thymio2_pairing_write_dongle_failed", "thymio2_pairing_write_robot_failed", };

  public static String name(int e) { return names[e]; }
}

