// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FirmwareUpgradeStatus extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static FirmwareUpgradeStatus getRootAsFirmwareUpgradeStatus(ByteBuffer _bb) { return getRootAsFirmwareUpgradeStatus(_bb, new FirmwareUpgradeStatus()); }
  public static FirmwareUpgradeStatus getRootAsFirmwareUpgradeStatus(ByteBuffer _bb, FirmwareUpgradeStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FirmwareUpgradeStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public mobsya.fb.NodeId nodeId() { return nodeId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeId(mobsya.fb.NodeId obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public double progress() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createFirmwareUpgradeStatus(FlatBufferBuilder builder,
      long requestId,
      int nodeIdOffset,
      double progress) {
    builder.startTable(3);
    FirmwareUpgradeStatus.addProgress(builder, progress);
    FirmwareUpgradeStatus.addNodeId(builder, nodeIdOffset);
    FirmwareUpgradeStatus.addRequestId(builder, requestId);
    return FirmwareUpgradeStatus.endFirmwareUpgradeStatus(builder);
  }

  public static void startFirmwareUpgradeStatus(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNodeId(FlatBufferBuilder builder, int nodeIdOffset) { builder.addOffset(1, nodeIdOffset, 0); }
  public static void addProgress(FlatBufferBuilder builder, double progress) { builder.addDouble(2, progress, 0.0); }
  public static int endFirmwareUpgradeStatus(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FirmwareUpgradeStatus get(int j) { return get(new FirmwareUpgradeStatus(), j); }
    public FirmwareUpgradeStatus get(FirmwareUpgradeStatus obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

