// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Ask the server to give this client sole ownership of the node.
 * This needs to be done once before sending mutating instructions to the node
 * The lock remain until the client disconnect, the device disconnect or a UnlockNode message is sent
 * Once locked, the node appears busy to all clients.
 */
@SuppressWarnings("unused")
public final class LockNode extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static LockNode getRootAsLockNode(ByteBuffer _bb) { return getRootAsLockNode(_bb, new LockNode()); }
  public static LockNode getRootAsLockNode(ByteBuffer _bb, LockNode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LockNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public mobsya.fb.NodeId nodeId() { return nodeId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeId(mobsya.fb.NodeId obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createLockNode(FlatBufferBuilder builder,
      long requestId,
      int nodeIdOffset) {
    builder.startTable(2);
    LockNode.addNodeId(builder, nodeIdOffset);
    LockNode.addRequestId(builder, requestId);
    return LockNode.endLockNode(builder);
  }

  public static void startLockNode(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNodeId(FlatBufferBuilder builder, int nodeIdOffset) { builder.addOffset(1, nodeIdOffset, 0); }
  public static int endLockNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LockNode get(int j) { return get(new LockNode(), j); }
    public LockNode get(LockNode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

