// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 *A node id
 */
@SuppressWarnings("unused")
public final class NodeId extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static NodeId getRootAsNodeId(ByteBuffer _bb) { return getRootAsNodeId(_bb, new NodeId()); }
  public static NodeId getRootAsNodeId(ByteBuffer _bb, NodeId obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NodeId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int idLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector idVector() { return idVector(new ByteVector()); }
  public ByteVector idVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createNodeId(FlatBufferBuilder builder,
      int idOffset) {
    builder.startTable(1);
    NodeId.addId(builder, idOffset);
    return NodeId.endNodeId(builder);
  }

  public static void startNodeId(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static int createIdVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createIdVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startIdVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endNodeId(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NodeId get(int j) { return get(new NodeId(), j); }
    public NodeId get(NodeId obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

