// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

/**
 * The Type of a node
 * A node can designate either a robot, a simulator, each with various capabilities.
 */
@SuppressWarnings("unused")
public final class NodeType {
  private NodeType() { }
  public static final int Thymio2 = 0;
  public static final int Thymio2Wireless = 1;
  public static final int SimulatedThymio2 = 2;
  public static final int DummyNode = 3;
  public static final int UnknownType = 4;

  public static final String[] names = { "Thymio2", "Thymio2Wireless", "SimulatedThymio2", "DummyNode", "UnknownType", };

  public static String name(int e) { return names[e]; }
}

