// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

/**
 * Capabilities of a node
 * What a client can do with a node may depends on permissions, firmware version, type of node/device, etc
 */
@SuppressWarnings("unused")
public final class NodeCapability {
  private NodeCapability() { }
  public static final int Rename = 1;
  public static final int ForceResetAndStop = 2;
  public static final int FirwmareUpgrade = 4;

  public static final String[] names = { "Rename", "ForceResetAndStop", "", "FirwmareUpgrade", };

  public static String name(int e) { return names[e - Rename]; }
}

