// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

/**
 * The status of a node represents whether the node is connected and available.
 */
@SuppressWarnings("unused")
public final class NodeStatus {
  private NodeStatus() { }
  /**
   * The status is unknown, this denotes a programmation error or a bug
   */
  public static final int unknown = 0;
  /**
   * The node is just connected. However, sending code or requesting a VM desciption is unspecified in this state
   */
  public static final int connected = 1;
  /**
   * The node is available. It needs to be sent a LockNode message before any action that would mutate it state, such as sending code can take place
   */
  public static final int available = 2;
  /**
   * The node is busy - this will be sent to all clients, except the one who locked the node
   */
  public static final int busy = 3;
  /**
   * The node is ready - this will be sent the client that optained a lock on the node
   */
  public static final int ready = 4;
  /**
   * The node is disconnected. Any reference to it will be destroyed on the server side, and sending further messages to it will fail
   */
  public static final int disconnected = 5;

  public static final String[] names = { "unknown", "connected", "available", "busy", "ready", "disconnected", };

  public static String name(int e) { return names[e]; }
}

