// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class ProgrammingLanguage {
  private ProgrammingLanguage() { }
  public static final int Aseba = 1;
  public static final int Aesl = 2;

  public static final String[] names = { "Aseba", "Aesl", };

  public static String name(int e) { return names[e - Aseba]; }
}

