// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Set a new name for this nùode
 */
@SuppressWarnings("unused")
public final class RenameNode extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static RenameNode getRootAsRenameNode(ByteBuffer _bb) { return getRootAsRenameNode(_bb, new RenameNode()); }
  public static RenameNode getRootAsRenameNode(ByteBuffer _bb, RenameNode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RenameNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public mobsya.fb.NodeId nodeId() { return nodeId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeId(mobsya.fb.NodeId obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String newName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer newNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer newNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createRenameNode(FlatBufferBuilder builder,
      long requestId,
      int nodeIdOffset,
      int newNameOffset) {
    builder.startTable(3);
    RenameNode.addNewName(builder, newNameOffset);
    RenameNode.addNodeId(builder, nodeIdOffset);
    RenameNode.addRequestId(builder, requestId);
    return RenameNode.endRenameNode(builder);
  }

  public static void startRenameNode(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNodeId(FlatBufferBuilder builder, int nodeIdOffset) { builder.addOffset(1, nodeIdOffset, 0); }
  public static void addNewName(FlatBufferBuilder builder, int newNameOffset) { builder.addOffset(2, newNameOffset, 0); }
  public static int endRenameNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RenameNode get(int j) { return get(new RenameNode(), j); }
    public RenameNode get(RenameNode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

