// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Modify the value of specified variables
 */
@SuppressWarnings("unused")
public final class SetVariables extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static SetVariables getRootAsSetVariables(ByteBuffer _bb) { return getRootAsSetVariables(_bb, new SetVariables()); }
  public static SetVariables getRootAsSetVariables(ByteBuffer _bb, SetVariables obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetVariables __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public mobsya.fb.NodeId nodeOrGroupId() { return nodeOrGroupId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeOrGroupId(mobsya.fb.NodeId obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public mobsya.fb.NodeVariable vars(int j) { return vars(new mobsya.fb.NodeVariable(), j); }
  public mobsya.fb.NodeVariable vars(mobsya.fb.NodeVariable obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int varsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public mobsya.fb.NodeVariable varsByKey(String key) { int o = __offset(8); return o != 0 ? mobsya.fb.NodeVariable.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public mobsya.fb.NodeVariable varsByKey(mobsya.fb.NodeVariable obj, String key) { int o = __offset(8); return o != 0 ? mobsya.fb.NodeVariable.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public mobsya.fb.NodeVariable.Vector varsVector() { return varsVector(new mobsya.fb.NodeVariable.Vector()); }
  public mobsya.fb.NodeVariable.Vector varsVector(mobsya.fb.NodeVariable.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createSetVariables(FlatBufferBuilder builder,
      long requestId,
      int nodeOrGroupIdOffset,
      int varsOffset) {
    builder.startTable(3);
    SetVariables.addVars(builder, varsOffset);
    SetVariables.addNodeOrGroupId(builder, nodeOrGroupIdOffset);
    SetVariables.addRequestId(builder, requestId);
    return SetVariables.endSetVariables(builder);
  }

  public static void startSetVariables(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNodeOrGroupId(FlatBufferBuilder builder, int nodeOrGroupIdOffset) { builder.addOffset(1, nodeOrGroupIdOffset, 0); }
  public static void addVars(FlatBufferBuilder builder, int varsOffset) { builder.addOffset(2, varsOffset, 0); }
  public static int createVarsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVarsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSetVariables(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetVariables get(int j) { return get(new SetVariables(), j); }
    public SetVariables get(SetVariables obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

