// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Thymio2WirelessDonglesChanged extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Thymio2WirelessDonglesChanged getRootAsThymio2WirelessDonglesChanged(ByteBuffer _bb) { return getRootAsThymio2WirelessDonglesChanged(_bb, new Thymio2WirelessDonglesChanged()); }
  public static Thymio2WirelessDonglesChanged getRootAsThymio2WirelessDonglesChanged(ByteBuffer _bb, Thymio2WirelessDonglesChanged obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Thymio2WirelessDonglesChanged __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public mobsya.fb.Thymio2WirelessDongle dongles(int j) { return dongles(new mobsya.fb.Thymio2WirelessDongle(), j); }
  public mobsya.fb.Thymio2WirelessDongle dongles(mobsya.fb.Thymio2WirelessDongle obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int donglesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public mobsya.fb.Thymio2WirelessDongle.Vector donglesVector() { return donglesVector(new mobsya.fb.Thymio2WirelessDongle.Vector()); }
  public mobsya.fb.Thymio2WirelessDongle.Vector donglesVector(mobsya.fb.Thymio2WirelessDongle.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createThymio2WirelessDonglesChanged(FlatBufferBuilder builder,
      int donglesOffset) {
    builder.startTable(1);
    Thymio2WirelessDonglesChanged.addDongles(builder, donglesOffset);
    return Thymio2WirelessDonglesChanged.endThymio2WirelessDonglesChanged(builder);
  }

  public static void startThymio2WirelessDonglesChanged(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addDongles(FlatBufferBuilder builder, int donglesOffset) { builder.addOffset(0, donglesOffset, 0); }
  public static int createDonglesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDonglesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endThymio2WirelessDonglesChanged(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Thymio2WirelessDonglesChanged get(int j) { return get(new Thymio2WirelessDonglesChanged(), j); }
    public Thymio2WirelessDonglesChanged get(Thymio2WirelessDonglesChanged obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

