// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Thymio2WirelessDongle extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Thymio2WirelessDongle getRootAsThymio2WirelessDongle(ByteBuffer _bb) { return getRootAsThymio2WirelessDongle(_bb, new Thymio2WirelessDongle()); }
  public static Thymio2WirelessDongle getRootAsThymio2WirelessDongle(ByteBuffer _bb, Thymio2WirelessDongle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Thymio2WirelessDongle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public mobsya.fb.NodeId dongleId() { return dongleId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId dongleId(mobsya.fb.NodeId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int dongleNode() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int networkId() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int channelId() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createThymio2WirelessDongle(FlatBufferBuilder builder,
      int dongleIdOffset,
      int dongleNode,
      int networkId,
      int channelId) {
    builder.startTable(4);
    Thymio2WirelessDongle.addDongleId(builder, dongleIdOffset);
    Thymio2WirelessDongle.addNetworkId(builder, networkId);
    Thymio2WirelessDongle.addDongleNode(builder, dongleNode);
    Thymio2WirelessDongle.addChannelId(builder, channelId);
    return Thymio2WirelessDongle.endThymio2WirelessDongle(builder);
  }

  public static void startThymio2WirelessDongle(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addDongleId(FlatBufferBuilder builder, int dongleIdOffset) { builder.addOffset(0, dongleIdOffset, 0); }
  public static void addDongleNode(FlatBufferBuilder builder, int dongleNode) { builder.addShort(1, (short) dongleNode, (short) 0); }
  public static void addNetworkId(FlatBufferBuilder builder, int networkId) { builder.addShort(2, (short) networkId, (short) 0); }
  public static void addChannelId(FlatBufferBuilder builder, int channelId) { builder.addByte(3, (byte) channelId, (byte) 0); }
  public static int endThymio2WirelessDongle(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Thymio2WirelessDongle get(int j) { return get(new Thymio2WirelessDongle(), j); }
    public Thymio2WirelessDongle get(Thymio2WirelessDongle obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

