// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Thymio2WirelessDonglePairingResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Thymio2WirelessDonglePairingResponse getRootAsThymio2WirelessDonglePairingResponse(ByteBuffer _bb) { return getRootAsThymio2WirelessDonglePairingResponse(_bb, new Thymio2WirelessDonglePairingResponse()); }
  public static Thymio2WirelessDonglePairingResponse getRootAsThymio2WirelessDonglePairingResponse(ByteBuffer _bb, Thymio2WirelessDonglePairingResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Thymio2WirelessDonglePairingResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long requestId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int networkId() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int channelId() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createThymio2WirelessDonglePairingResponse(FlatBufferBuilder builder,
      long requestId,
      int networkId,
      int channelId) {
    builder.startTable(3);
    Thymio2WirelessDonglePairingResponse.addRequestId(builder, requestId);
    Thymio2WirelessDonglePairingResponse.addNetworkId(builder, networkId);
    Thymio2WirelessDonglePairingResponse.addChannelId(builder, channelId);
    return Thymio2WirelessDonglePairingResponse.endThymio2WirelessDonglePairingResponse(builder);
  }

  public static void startThymio2WirelessDonglePairingResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addRequestId(FlatBufferBuilder builder, long requestId) { builder.addInt(0, (int) requestId, (int) 0L); }
  public static void addNetworkId(FlatBufferBuilder builder, int networkId) { builder.addShort(1, (short) networkId, (short) 0); }
  public static void addChannelId(FlatBufferBuilder builder, int channelId) { builder.addByte(2, (byte) channelId, (byte) 0); }
  public static int endThymio2WirelessDonglePairingResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Thymio2WirelessDonglePairingResponse get(int j) { return get(new Thymio2WirelessDonglePairingResponse(), j); }
    public Thymio2WirelessDonglePairingResponse get(Thymio2WirelessDonglePairingResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

