// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VariablesChanged extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static VariablesChanged getRootAsVariablesChanged(ByteBuffer _bb) { return getRootAsVariablesChanged(_bb, new VariablesChanged()); }
  public static VariablesChanged getRootAsVariablesChanged(ByteBuffer _bb, VariablesChanged obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VariablesChanged __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public mobsya.fb.NodeId nodeId() { return nodeId(new mobsya.fb.NodeId()); }
  public mobsya.fb.NodeId nodeId(mobsya.fb.NodeId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public mobsya.fb.NodeVariable vars(int j) { return vars(new mobsya.fb.NodeVariable(), j); }
  public mobsya.fb.NodeVariable vars(mobsya.fb.NodeVariable obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int varsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public mobsya.fb.NodeVariable varsByKey(String key) { int o = __offset(6); return o != 0 ? mobsya.fb.NodeVariable.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public mobsya.fb.NodeVariable varsByKey(mobsya.fb.NodeVariable obj, String key) { int o = __offset(6); return o != 0 ? mobsya.fb.NodeVariable.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public mobsya.fb.NodeVariable.Vector varsVector() { return varsVector(new mobsya.fb.NodeVariable.Vector()); }
  public mobsya.fb.NodeVariable.Vector varsVector(mobsya.fb.NodeVariable.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  /**
   * unix timestamp ( miliseconds) of when the variables were modified - or 0 if unspecified
   */
  public long timestamp() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createVariablesChanged(FlatBufferBuilder builder,
      int nodeIdOffset,
      int varsOffset,
      long timestamp) {
    builder.startTable(3);
    VariablesChanged.addTimestamp(builder, timestamp);
    VariablesChanged.addVars(builder, varsOffset);
    VariablesChanged.addNodeId(builder, nodeIdOffset);
    return VariablesChanged.endVariablesChanged(builder);
  }

  public static void startVariablesChanged(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNodeId(FlatBufferBuilder builder, int nodeIdOffset) { builder.addOffset(0, nodeIdOffset, 0); }
  public static void addVars(FlatBufferBuilder builder, int varsOffset) { builder.addOffset(1, varsOffset, 0); }
  public static int createVarsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVarsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(2, timestamp, 0L); }
  public static int endVariablesChanged(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VariablesChanged get(int j) { return get(new VariablesChanged(), j); }
    public VariablesChanged get(VariablesChanged obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

