// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class VMExecutionError {
  private VMExecutionError() { }
  public static final short NoError = 0;
  public static final short Killed = 1;
  public static final short OutOfBoundAccess = 2;
  public static final short DivisionByZero = 3;
  public static final short GenericError = 4;

  public static final String[] names = { "NoError", "Killed", "OutOfBoundAccess", "DivisionByZero", "GenericError", };

  public static String name(int e) { return names[e]; }
}

