// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class VMExecutionStateCommand {
  private VMExecutionStateCommand() { }
  public static final short Stop = 0;
  public static final short Run = 1;
  public static final short Step = 2;
  public static final short StepToNextLine = 3;
  public static final short Pause = 4;
  public static final short Reset = 5;
  public static final short Reboot = 6;
  public static final short Suspend = 7;
  public static final short WriteProgramToDeviceMemory = 8;

  public static final String[] names = { "Stop", "Run", "Step", "StepToNextLine", "Pause", "Reset", "Reboot", "Suspend", "WriteProgramToDeviceMemory", };

  public static String name(int e) { return names[e]; }
}

