// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class VMExecutionState {
  private VMExecutionState() { }
  public static final short Stopped = 0;
  public static final short Running = 1;
  public static final short Paused = 2;

  public static final String[] names = { "Stopped", "Running", "Paused", };

  public static String name(int e) { return names[e]; }
}

