// automatically generated by the FlatBuffers compiler, do not modify

package mobsya.fb;

@SuppressWarnings("unused")
public final class WatchableInfo {
  private WatchableInfo() { }
  public static final int StopMonitoring = 0;
  public static final int Variables = 1;
  public static final int Events = 2;
  public static final int VMExecutionState = 4;
  public static final int SharedEventsDescription = 8;
  public static final int SharedVariables = 16;
  public static final int Scratchpads = 32;

  public static final String[] names = { "StopMonitoring", "Variables", "Events", "", "VMExecutionState", "", "", "", "SharedEventsDescription", "", "", "", "", "", "", "", "SharedVariables", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Scratchpads", };

  public static String name(int e) { return names[e]; }
}

